commonLabels:
  appname: wordpress-1
resources:
- ../../bases/wordpress
namespace: wordpress-1
patchesStrategicMerge:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: knights007/wordpress
  newTag: v1.0.1
- name: knights007:wordpress
  newTag: v1.0.2
